Add wasm support
umut-sahin/dotlr pull request #10
Opened 2024-09-13 17:45 UTC by Specy

I'll open this PR for adding wasm support to the lib plus a TS wrapper over it to make a more javascripty idiomatic experience.

This PR is still ongoing, for now i added basic support for creating a grammar and a parser, still have to work out the rest, there will be a lot of serialization work going on!
It shouldn't be that hard to add the wasm layer, might take a few days

2024-09-13 19:21 UTC, Specy commented
I Added most of the typings and features, Grammar and Parser should mostly be completed, i only lack some typings for the various tables as i'm not sure how to type IndexMap and IndexSet, i'll have to see what serde spits out as json.

2024-09-14 08:24 UTC, umut-sahin commented
IndexMap and IndexSet are for preserving insertion order. So that the output format is deterministic. Other than this they are pretty much the same as HashMap and HashSet, so you should be able to save it as JSON object.

Ordering of JavaScript objects are not guaranteed, so you can't just load the object while preserving order. However, there are global [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) and [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) classes, which have the exact same semantics as IndexMap and IndexSet, so I'd look into those!

2024-09-14 08:27 UTC, Specy commented
Seems like wasm_bindgen correctly converted IndexMap and IndexSet to a Map and an array, the set wouldn't make too much sense in javascript so i'm leaving it as an array.

The library should be pretty much complete by now, i've added the last typings and some documentation for the readme of the npm module. I've been trying it on my website and it seems to be working good! i'll link it here after i get to publish a beta version of it

2024-09-14 08:54 UTC, umut-sahin requested changes
One thing to note, release process should be automated in the CI to publish to NPM. Also, the versions should match between crates.io and npm. This would allow us to have a unified version and compatibility between versions. #11 would do the same with pypi.

Another small thing is I'd prefer `ts-lib` directory to be moved to `bindings/typescript` as I'm thinking of having `bindings/python` as well.

I left a partial review, I need to head out for now, sorry. I'll do another review once you say it's ready for round 2.

Let me know if you have any questions, or need help with something!

Lastly, thanks for doing this, this is really valuable and I can't wait to see the website :heart_hands:

2024-09-14 08:54 UTC, umut-sahin commented on Cargo.toml
> +colored = { version = "2.1", optional = true }
Can you make this a non-wasm dependency instead of managing it with features:
```toml
[target.'cfg(not(target_family = "wasm"))'.dependencies]
colored = { version = "2.1" }
```

2024-09-14 08:54 UTC, umut-sahin commented on Cargo.toml
> +serde-wasm-bindgen = { version = "0.6.5", optional = true }
And make these wasm-only dependencies:
```toml
[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen = { version = "0.2.83" }
console_error_panic_hook = { version = "0.1.1" }
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = { version = "0.6.5" }
```

2024-09-14 08:54 UTC, umut-sahin commented on Cargo.toml
> +serde-wasm-bindgen = { version = "0.6.5", optional = true }
Maybe not `serde` as it could be useful for all users.

2024-09-14 08:54 UTC, umut-sahin commented on Cargo.toml
> +]
This will no longer be necessary. `cfg(target_family = "wasm")` can be used instead.

2024-09-14 08:54 UTC, umut-sahin commented on examples/calculator.rs
> +    let cursor = format!("{} ", str_bold(str_cyan(">")));
With the mock trait that I shared [here](https://github.com/umut-sahin/dotlr/issues/8#issuecomment-2350904437), there is no need to change this.

2024-09-14 08:54 UTC, umut-sahin commented on src/errors.rs
> +        str_cyan(format_smolstr!("{}", column)),
Let's use the mock trait to avoid changing these.

2024-09-14 09:48 UTC, Specy commented on Cargo.toml
> +serde-wasm-bindgen = { version = "0.6.5", optional = true }
Should serde be a implemented by default or left in a feature flag?

2024-09-14 10:00 UTC, umut-sahin commented on Cargo.toml
> +serde-wasm-bindgen = { version = "0.6.5", optional = true }
I'd go for behind feature a feature flag. It's not essential.

2024-09-14 10:09 UTC, Specy commented on Cargo.toml
> +serde-wasm-bindgen = { version = "0.6.5", optional = true }
I don't have too much experience in the toml configs, how would i go at enabling the serde feature when the target arch is wasm, and also disabel the "default" feature (as that imports the modules that give errors)?

2024-09-14 12:05 UTC, Specy commented on Cargo.toml
> +serde-wasm-bindgen = { version = "0.6.5", optional = true }
Ok seems like it's not possible to conditionally choose the default features based off arch, `default = ["repl"]`, should i remove the default?

2024-09-16 20:22 UTC, Specy commented on Cargo.toml
> +]
the user might want to implement it's own wasm bindings so targeting the arch is probably undesirable, i'd keep the feature flag

2024-09-17 06:54 UTC, umut-sahin requested changes
Sorry for the late review, it's been a busy week. 

There are some stuff to change, but overall, it looks preem!

Let me know if you have any question, or if you want help with anything.

2024-09-17 06:54 UTC, umut-sahin commented on Cargo.toml
>  [dependencies]
Could you keep the dependencies ordered, to make them easier to find.

2024-09-17 06:54 UTC, umut-sahin commented on Cargo.toml
> +serde-wasm-bindgen = { version = "0.6.5", optional = true }
I can't think of any use case in which the target arch is not wasm and `wasm-bindgen` is dependent upon. 

That being said, I'm okay with the feature flag as well. So let's go!

2024-09-17 06:54 UTC, umut-sahin commented on Cargo.toml
> +]
I wonder if there is a way to use `serde` as the feature name. It's not possible right now I guess as it's the name of a dependency, but what if we rename the dependency? See https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#renaming-dependencies-in-cargotoml.

Maybe we can:
```
[dependencies]
serde_renamed = { version = "...", package = "serde" }
...
serde = [
    "serde_renamed",
    "smol_str/serde",
    "smallvec/serde",
    "indexmap/serde",
]
```
Wdyt?

2024-09-17 06:54 UTC, umut-sahin commented on Cargo.toml
> +    "serde_support"
Could you re-order these as well? I know it's minor but it adds up over time especially with many dependencies/features.

2024-09-17 06:54 UTC, umut-sahin commented on bindings/typescript/.gitignore
> +*.sw?
I guess this file doesn't have a trailing newline, which should be the case (I thought I had CI checks for this but apparently not).

2024-09-17 06:54 UTC, umut-sahin commented on bindings/typescript/README.md
> +`dotlr` is a library for working with grammars and parsers in TypeScript. It provides an interface to parse grammars, generate parsing tables, and process input strings using parsers like LR1 and LAL
> parsers like LR1 and LALR

I'd use `LR(1)` and `LALR(1)`, they are used like that throughout the project.

2024-09-17 06:54 UTC, umut-sahin commented on bindings/typescript/README.md
> +`dotlr` is a library for working with grammars and parsers in TypeScript. It provides an interface to parse grammars, generate parsing tables, and process input strings using parsers like LR1 and LAL
> making it suitable for building interpreters or compilers

I'm not sure that's the case, parsing itself is not optimized at all :sweat_smile: 

The purpose of the project is to learn and teach complex parsers, I wouldn't recommend using it in production (at least not yet).

2024-09-17 06:54 UTC, umut-sahin commented on bindings/typescript/README.md
> +5. [Using the LALR Parser](#using-the-lalr-parser)
Same thing about the notation.

2024-09-17 06:54 UTC, umut-sahin commented on bindings/typescript/README.md
> +```
Very nice!

2024-09-17 06:54 UTC, umut-sahin commented on bindings/typescript/README.md
> +```
Very nice!

2024-09-17 06:54 UTC, umut-sahin commented on bindings/typescript/README.md
> +`;
Could you put some blank spaces lines around the actual definition, it makes it better to read IMO.

2024-09-17 06:54 UTC, umut-sahin commented on bindings/typescript/README.md
> +const grammarResult = Grammar.fromGrammar(grammarStr);
`Grammar.fromGrammar` feels a little bit off. Why not `Grammar.parse`?

2024-09-17 06:54 UTC, umut-sahin commented on bindings/typescript/build.js
> +init()
Same thing with trailing newlines at the end of files.

2024-09-17 06:54 UTC, umut-sahin commented on bindings/typescript/package-lock.json
> +{
Is it recommended for npm libraries to include the lockfile? It isn't recommended by Rust, so I've omitted `Cargo.lock`.

2024-09-17 06:54 UTC, umut-sahin commented on bindings/typescript/package.json
> +  "description": "",
Please copy the description from `Cargo.toml`.

2024-09-17 06:54 UTC, umut-sahin commented on bindings/typescript/package.json
> +  "version": "0.1.16",
And as I said in a previous comment, let's keep the versions synced between Rust crate and NPM package.

And also automate the release process in the CI.

The workflow should be:
- Make some changes
- When ready bump the versions in `Cargo.toml` and `package.json`
- Push and wait for the CI to be green
- Create a tag with the same version
- Push the tag
- CI would do the release to both NPM and Crates.io

2024-09-17 06:54 UTC, umut-sahin commented on bindings/typescript/src/utils.ts
> +}
This logic is already implemented in the rust side, it'd be better to expose it in `Token` (e.g., `Token.toString()`).

2024-09-17 06:54 UTC, umut-sahin commented on bindings/typescript/src/utils.ts
> +}
(same for below)

2024-09-17 06:54 UTC, umut-sahin commented on src/errors.rs
> +        #[cfg_attr(feature = "serde", serde(skip))] // TODO improve this
What's keeping `Parser` from (de)serialized?

2024-09-17 06:54 UTC, umut-sahin commented on bindings/typescript/src/utils.ts
> +}
Okay, reading below I see why it's like this. I guess it's okay, it's just something to remember when updating something in the Rust side.

2024-09-17 06:54 UTC, umut-sahin commented on src/grammar.rs
> +    #[cfg_attr(feature = "serde", derive(Serialize))]
This is an internal enum, it doesn't need to be serialized, like ever.

2024-09-17 06:54 UTC, umut-sahin commented on src/utils.rs
> +}
This needs documentation.

2024-09-17 07:02 UTC, Specy commented on bindings/typescript/package.json
> +  "version": "0.1.16",
How would you handle version changes that don't affect both packages? As in, let's say I add a new feature to the typescript version, or a bug fix, but this does not affect the rust crate (the opposite is not true), would the version of the rust crate be bumped too?

2024-09-17 08:40 UTC, Specy commented on bindings/typescript/package-lock.json
> +{
yes, usually it helps with package resolution, i always include it

2024-09-18 15:33 UTC, Specy commented on bindings/typescript/README.md
Reminder for myself, redo the whole readme including the .parse in lalr and lr1 I've accidentally replaced their strings

2024-09-22 19:47 UTC, umut-sahin requested changes
Could you change:
```
  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [ conformance, test ]

    name: Publish
```
to
```
  publish-crates-io:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [ conformance, test ]

    name: Publish to Crates.io
```

This is probably the last review. 

Thanks :partying_face:

2024-09-22 19:47 UTC, umut-sahin commented on .github/workflows/ci.yml
> +  publish_npm:
Let's use `publish-npm`.

2024-09-22 19:47 UTC, umut-sahin commented on .github/workflows/ci.yml
> +    name: Publish NPM Package
And `Publish to NPM`.

2024-09-22 19:47 UTC, umut-sahin commented on .github/workflows/ci.yml
> +          node-version: '20'
Any specific reason for `20`? Will it work on other versions?

2024-09-22 19:47 UTC, umut-sahin commented on .github/workflows/ci.yml
> +        run: cd /bindings/typescript
I think it should be `cd bindings/typescript`, trailing `/` feels like it would result in failure.

2024-09-22 19:47 UTC, umut-sahin commented on .github/workflows/ci.yml
> +      - name: Run Build
Let's just call this `Build`.

2024-09-22 19:47 UTC, umut-sahin commented on .github/workflows/ci.yml
> +      - name: Publish to npm
And `Publish`, we're already in the job for NPM, no need to mention it again IMO.

2024-09-22 19:47 UTC, umut-sahin commented on .github/workflows/ci.yml
> +          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
Send me the `NPM_TOKEN` in private. I'll make it a repo secret.

2024-09-22 19:47 UTC, umut-sahin commented on .github/workflows/ci.yml
> +          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
Also, don't forget the trailing newline, CI will be red otherwise.

2024-09-22 19:47 UTC, umut-sahin commented on bindings/typescript/README.md
> +`dotlr` is a library for working with grammars and parsers in TypeScript. It provides an interface to parse grammars, generate parsing tables, and process input strings using parsers like LR(1) and L
I'd say:
```
`dotlr` is a library for creating and inspecting LR family of parsers in TypeScript. It provides an interface to parse grammars, generate parsing tables, and trace parsing of inputs. The library leverages WebAssembly (WASM) to ensure efficient parsing.
```

2024-09-22 19:47 UTC, umut-sahin commented on bindings/typescript/README.md
> +It is focused on providing educational resources for learning about parsing algorithms and compiler construction. The library is designed to be easy to use and understand, making it ideal for student
Lovely!

2024-09-22 19:47 UTC, umut-sahin commented on bindings/typescript/README.md
> +
Single blank line is enough. This applies to the rest of the file.

2024-09-22 19:47 UTC, umut-sahin commented on bindings/typescript/README.md
> +5. [Using the LALR(1) Parser](#using-the-lalr1-parser)
`Creating LR(1) Parser of the Grammar`
`Creating LALR(1) Parser of the Grammar`

2024-09-22 19:47 UTC, umut-sahin commented on bindings/typescript/README.md
> +    - [Tracing](#tracing)
Let's just have `Tokenization` and `Parsing`, and mention tracing in the `Parsing` section.

2024-09-22 19:47 UTC, umut-sahin commented on bindings/typescript/README.md
> +- **getProductions()**: Retrieves the list of productions (rules) defined in the grammar.
Let's use:
`grammar.getSymbols()`
`grammar.getProductions()`

2024-09-22 19:47 UTC, umut-sahin commented on bindings/typescript/README.md
> +import { Grammar, LR1Parser, LALRParser } from 'dotlr';
Why two parser types? It diverges a bit from the underlying library. Maybe we can put an `Algorithm` enum inside `Parser` to distinguish the parser, if you need that information.

2024-09-22 19:47 UTC, umut-sahin commented on bindings/typescript/README.md
> +- **getProductions()**: Retrieves the list of productions (rules) defined in the grammar.
(same below)

2024-09-22 19:47 UTC, umut-sahin commented on bindings/typescript/package-lock.json
> +{
I was asking because it's not recommended for libraries to include `Cargo.lock`. But if you're sure that, it's not the case with NPM, feel free to leave it. Just let us know here!

2024-09-22 19:47 UTC, umut-sahin commented on bindings/typescript/package.json
> +    "build-wasm:no-test": "cd .. && wasm-pack build --out-dir bindings/typescript/src/pkg --out-name dotlr --features wasm --no-default-features",
Should these be using the `--release` flag? We could be leaving a lot of performance in the table.

2024-09-22 19:47 UTC, umut-sahin commented on bindings/typescript/package.json
> +}
Trailing newline please.

2024-09-22 19:47 UTC, umut-sahin commented on bindings/typescript/src/index.ts
> +> {
What's the reason behind these being generic?

2024-09-22 19:47 UTC, umut-sahin commented on bindings/typescript/src/index.ts
> +}
Will this come in a subsequent PR, or in this one?

2024-09-22 19:47 UTC, umut-sahin commented on bindings/typescript/src/types.ts
> +//TODO not sure how to type Symbol
Why are these in a different file, compared to the types defined in `index.ts`?

2024-09-22 19:47 UTC, umut-sahin commented on bindings/typescript/src/utils.ts
> +}
It'd be really nice if we can find a way around this. I'm not sure I understand why we're not doing `#[cfg_attr(feature = "wasm", wasm_bindgen)]` for almost all types and use them directly.

2024-09-22 19:47 UTC, umut-sahin commented on src/utils.rs
> +};
Let's just have `use crate::prelude::*;` here and export these from `prelude`. It'll be easier to work with.

2024-09-22 19:47 UTC, umut-sahin commented on src/utils.rs
> +}
```
/// Serialize a map of regex objects to a map of regex strings.
```

2024-09-22 20:05 UTC, Specy commented on .github/workflows/ci.yml
> +          node-version: '20'
Yes it should work in other versions, I've put 20 as it's the LTS

2024-09-22 21:34 UTC, Specy commented on bindings/typescript/README.md
> +import { Grammar, LR1Parser, LALRParser } from 'dotlr';
Feels more straightforward, you don't really ever "decide" to turn a LR(1) parser to LALR, your goal from the beginning is creating a LALR parser, so having a class reflect that seems more intuitive

2024-09-22 21:36 UTC, Specy commented on bindings/typescript/package.json
> +    "build-wasm:no-test": "cd .. && wasm-pack build --out-dir bindings/typescript/src/pkg --out-name dotlr --features wasm --no-default-features",
Wasm pack always uses release build

2024-09-22 21:37 UTC, Specy commented on bindings/typescript/src/index.ts
> +> {
Being able to type the strings for the Terminals (T), NonTerminals (NT) and regex (R). 

This way once you parse a string, or use the grammar, you have type safety over the generated parse tree

2024-09-22 21:38 UTC, Specy commented on bindings/typescript/src/index.ts
> +}
Future PR I guess? For when we will implement the LR0 parser

2024-09-22 21:40 UTC, Specy commented on bindings/typescript/src/types.ts
> +//TODO not sure how to type Symbol
The wasm library is imported using top level await, which might break SSR in some frameworks, and must make the client be a client only route, by adding the types to a different file you are able to import the typings from any file without having to worry about importing the wasm module too

2024-09-23 10:12 UTC, Specy commented on bindings/typescript/README.md
> +    - [Tracing](#tracing)
i've removed it altogether and moved it into the parsers itself

2024-09-28 07:54 UTC, umut-sahin commented on bindings/typescript/README.md
> +import { Grammar, LR1Parser, LALRParser } from 'dotlr';
Correct, but it's not what's happening in the underlying library. Let's merge it like this, and update the underling implementation to be similar, sounds good?

2024-09-28 07:54 UTC, umut-sahin commented on bindings/typescript/src/index.ts
> +}
Sure, please create an issue for these though.

2024-09-28 07:58 UTC, umut-sahin requested changes
Last request and we can merge!

Could you squash all of the commits to a single one with the message:
```
feat: add typescript bindings using wasm
```

CI needs to be green as well, of course.

2024-09-28 08:02 UTC, Specy commented on bindings/typescript/README.md
> +import { Grammar, LR1Parser, LALRParser } from 'dotlr';
Sure

2024-09-28 08:03 UTC, Specy commented on bindings/typescript/src/index.ts
> +}
There is one already

2024-09-29 10:53 UTC, umut-sahin approved these changes
Thanks for this amazing work, and sorry for the long review process. The time has come!

2024-09-29 10:53 UTC, merged