feat: add token span info, fixes #1 and #13
umut-sahin/dotlr pull request #15
Opened 2024-10-01 17:58 UTC by Specy

2024-10-09 20:48 UTC, umut-sahin commented
Sorry, it has been a busy week. I'll review it in this weekend, thanks!

2024-10-09 21:26 UTC, Specy commented
Sure

2024-10-12 10:07 UTC, umut-sahin requested changes
Let's move span related types and impls to their own module. Create `src/span.rs` and move related code there please.

I'll give another review once the PR is updated. Thanks!

2024-10-12 10:07 UTC, umut-sahin commented on src/parser.rs
> +    slice.chars().filter(|&c| c == '\n').count()
We don't need to iterate over chars, it should be okay to iterate over bytes and check for `\n` byte.

2024-10-12 10:07 UTC, umut-sahin commented on src/parser.rs
> +}
Let's move these to utils and document them.

2024-10-12 10:07 UTC, umut-sahin commented on src/parser.rs
> +    if line_num == 0 { offset - slice[..offset].rfind('\n').unwrap_or(1) - 1 } else { offset }
I'm not sure this would be accurate. If there is a multi-byte unicode character or a grapheme clusters, we'd be wildly off in our column calculations. Grapheme clusters are a beast on their own so we can safely ignore them, but it should work for `char`s at least.

2024-10-12 10:32 UTC, Specy commented on tests/parsing.rs
> +    assert_eq!(error.to_string(), "unexpected token / at [1:4] (expected one of '(', %f)");
> Why is the coloring a problem in grammar tests but not here?

it is a problem still, on my machine the tests don't pass because of that, but those tests needed changes for the CI to pass

2024-10-12 11:04 UTC, Specy commented on tests/parsing.rs
> +        "unexpected end of input at [1:6] (expected one of '^', '+', '-', '*', '/', ')')",
I had made the column 0 indexed instead of 1 indexed, i've changed that now

2024-10-12 12:14 UTC, Specy commented
I forgot to change the local package.json version back to v0.3.0, be careful when publishing, make sure to change it back to v0.3.1

2024-10-14 11:17 UTC, umut-sahin requested changes
We also need to test whether the returned spans are correct. Could you add/update tests to make sure spans are calculated correctly in `tests/parsing.rs`?

2024-10-14 11:17 UTC, umut-sahin commented on src/utils.rs
> +        let last_newline = rfind_utf8(&slice[..offset], '\n').unwrap_or(1);
I think this will be really really slow. Can't we pass it as a parameter and keep track of it during parsing?

2024-10-14 11:17 UTC, umut-sahin commented on src/utils.rs
> +/// The offset is the byte offset of the character in the slice.
I think there needs to be an empty documentation comment between these:
```
///
```

This will make sure it's not continuation of the title.

2024-10-14 11:17 UTC, umut-sahin commented on src/span.rs
> +/// Position information of a piece of text in the input string.
Let's move all documentations to the top.

2024-10-14 11:19 UTC, Specy commented on bindings/typescript/package.json
> -  "version": "0.3.0",
yes sorry i forgot to change it back when doing the local deployment

2024-10-14 11:21 UTC, Specy commented on src/tree.rs
> -impl<'i> Display for Tree<'i> {
I had a CI error because of the explicit lifetimes, should we change the clippy error to allow it?

2024-10-14 18:28 UTC, Specy commented
I have not added tests for the typescript lib because i'm getting error with the node environment running with wasm and it's a bit of a mess (love js sometimes) so i've left it for a future PR, but i've added the tokenization span test, only one but it covers many cases of where it could be buggy

2024-11-07 16:10 UTC, merged